import { motion } from "framer-motion";
import { FaBullseye, FaGlobeAsia } from "react-icons/fa";

function About() {
  return (
    <section
      id="about"
      className="relative py-24 overflow-hidden bg-gradient-to-b from-white to-green-50"
    >
      {/* Background Decorative Image */}
      <div
        className="absolute right-0 top-0 w-[500px] h-[500px] opacity-5 bg-no-repeat bg-contain"
        style={{ backgroundImage: "url('/about-bg.jpg')" }}
      />

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          viewport={{ once: true }}
        >
          {/* Section Title */}
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-8 text-slate-900 ">
            About Us
          </h2>

          {/* About Content */}
          <div className="max-w-5xl mx-auto">
            <p className="text-center text-gray-700 text-lg leading-9">
              <strong>Jabalpur E-Waste Cleaners</strong> is a professional
              e-waste collection, transportation and disposal organization
              committed to promoting a cleaner, greener and environmentally
              responsible future. We provide reliable solutions for the safe
              handling and management of electronic waste generated by
              hospitals, government departments, banks, educational
              institutions, corporate organizations and individual consumers.
            </p>

            <p className="text-center text-gray-700 text-lg leading-9 mt-6">
              Our services cover the collection and responsible disposal of
              computer systems, laptops, printers, motherboards, RAM,
              networking equipment, UPS systems, batteries, medical e-waste,
              lead apron scrap and various other electronic materials.
              Every collection is handled with proper documentation and
              environmentally compliant disposal practices.
            </p>

            <p className="text-center text-gray-700 text-lg leading-9 mt-6">
              At Jabalpur E-Waste Cleaners, our objective is not only to
              collect electronic waste but also to contribute towards reducing
              environmental pollution, conserving valuable resources and
              creating awareness about responsible e-waste management across
              Madhya Pradesh and beyond.
            </p>
          </div>

          {/* Mission & Vision Cards */}
          <div className="grid md:grid-cols-2 gap-8 mt-16">

            {/* Mission */}
            <motion.div
              whileHover={{ y: -8 }}
              className="
                relative
                overflow-hidden
                bg-white
                rounded-3xl
                shadow-xl
                border
                p-8
                transition-all
                duration-300
                hover:shadow-2xl
              "
            >
              {/* Left Border */}
              <div className="absolute left-0 top-0 h-full w-3 bg-gradient-to-b from-green-500 to-green-700 rounded-r-full"></div>

              {/* Background Icon */}
              <FaBullseye
                className="
                  absolute
                  right-6
                  top-6
                  text-green-100
                  text-[120px]
                  pointer-events-none
                "
              />

              <div className="relative pl-4">

                {/* Icon Badge */}
                <div className="
                  w-14
                  h-14
                  rounded-2xl
                  bg-green-100
                  flex
                  items-center
                  justify-center
                  mb-5
                ">
                  <FaBullseye className="text-green-700 text-2xl" />
                </div>

                <h3 className="text-2xl font-bold text-green-700 mb-5">
                  Our Mission
                </h3>

                <p className="text-gray-700 leading-8">
                  To promote environmental protection through safe,
                  responsible and sustainable e-waste management practices.
                  We aim to provide reliable collection, transportation and
                  disposal services that help organizations and individuals
                  manage electronic waste efficiently while minimizing its
                  environmental impact. Our commitment is to ensure every
                  electronic asset is handled with professionalism,
                  transparency and environmental responsibility.
                </p>

              </div>
            </motion.div>

            {/* Vision */}
            <motion.div
              whileHover={{ y: -8 }}
              className="
                relative
                overflow-hidden
                bg-white
                rounded-3xl
                shadow-xl
                border
                p-8
                transition-all
                duration-300
                hover:shadow-2xl
              "
            >
              {/* Left Border */}
              <div className="absolute left-0 top-0 h-full w-3 bg-gradient-to-b from-green-500 to-green-700 rounded-r-full"></div>

              {/* Background Icon */}
              <FaGlobeAsia
                className="
                  absolute
                  right-6
                  top-6
                  text-green-100
                  text-[120px]
                  pointer-events-none
                "
              />

              <div className="relative pl-4">

                {/* Icon Badge */}
                <div className="
                  w-14
                  h-14
                  rounded-2xl
                  bg-green-100
                  flex
                  items-center
                  justify-center
                  mb-5
                ">
                  <FaGlobeAsia className="text-green-700 text-2xl" />
                </div>

                <h3 className="text-2xl font-bold text-green-700 mb-5">
                  Our Vision
                </h3>

                <p className="text-gray-700 leading-8">
                  To become one of the most trusted and recognized
                  organizations in the field of e-waste management and
                  recycling across Madhya Pradesh. We envision a future where
                  responsible disposal and recycling of electronic waste
                  becomes a standard practice, contributing to cleaner cities,
                  healthier communities and a sustainable environment for
                  future generations.
                </p>

              </div>
            </motion.div>

          </div>
        </motion.div>
      </div>
    </section>
  );
}

export default About;